apiVersion: v1
items:
- apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"autoscaling/v2","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"labels":{"experiment":"h3-hpa-custom-metric"},"name":"product-service-hpa-custom","namespace":"ecommerce"},"spec":{"behavior":{"scaleDown":{"policies":[{"periodSeconds":15,"type":"Percent","value":100}],"stabilizationWindowSeconds":30},"scaleUp":{"policies":[{"periodSeconds":15,"type":"Pods","value":5}],"stabilizationWindowSeconds":0}},"maxReplicas":5,"metrics":[{"pods":{"metric":{"name":"http_requests_per_second"},"target":{"averageValue":"50","type":"AverageValue"}},"type":"Pods"}],"minReplicas":1,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"product-service"}}}
    creationTimestamp: "2026-04-07T11:21:47Z"
    labels:
      experiment: h3-hpa-custom-metric
    name: product-service-hpa-custom
    namespace: ecommerce
    resourceVersion: "1004456"
    uid: 9f8d349f-cfa0-4764-9d61-dba24b7d8dce
  spec:
    behavior:
      scaleDown:
        policies:
        - periodSeconds: 15
          type: Percent
          value: 100
        selectPolicy: Max
        stabilizationWindowSeconds: 30
      scaleUp:
        policies:
        - periodSeconds: 15
          type: Pods
          value: 5
        selectPolicy: Max
        stabilizationWindowSeconds: 0
    maxReplicas: 5
    metrics:
    - pods:
        metric:
          name: http_requests_per_second
        target:
          averageValue: "50"
          type: AverageValue
      type: Pods
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: product-service
  status:
    conditions:
    - lastTransitionTime: "2026-04-07T11:22:02Z"
      message: the HPA controller was able to get the target's current scale
      reason: SucceededGetScale
      status: "True"
      type: AbleToScale
    - lastTransitionTime: "2026-04-07T11:22:02Z"
      message: 'the HPA was unable to compute the replica count: unable to get metric
        http_requests_per_second: unable to fetch metrics from custom metrics API:
        the server could not find the metric http_requests_per_second for pods'
      reason: FailedGetPodsMetric
      status: "False"
      type: ScalingActive
    currentMetrics:
    - type: ""
    currentReplicas: 1
    desiredReplicas: 0
kind: List
metadata:
  resourceVersion: ""
