apiVersion: v1
items:
- apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"autoscaling/v2","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"labels":{"experiment":"h3-hpa-custom-metric"},"name":"product-service-hpa-custom","namespace":"ecommerce"},"spec":{"behavior":{"scaleDown":{"policies":[{"periodSeconds":15,"type":"Percent","value":100}],"stabilizationWindowSeconds":30},"scaleUp":{"policies":[{"periodSeconds":15,"type":"Pods","value":5}],"stabilizationWindowSeconds":0}},"maxReplicas":5,"metrics":[{"pods":{"metric":{"name":"http_requests_per_second"},"target":{"averageValue":"5","type":"AverageValue"}},"type":"Pods"}],"minReplicas":1,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"product-service"}}}
    creationTimestamp: "2026-04-14T13:34:20Z"
    labels:
      experiment: h3-hpa-custom-metric
    name: product-service-hpa-custom
    namespace: ecommerce
    resourceVersion: "1629625"
    uid: e14590f3-6c2f-47f5-9d28-68a1dd2374ce
  spec:
    behavior:
      scaleDown:
        policies:
        - periodSeconds: 15
          type: Percent
          value: 100
        selectPolicy: Max
        stabilizationWindowSeconds: 30
      scaleUp:
        policies:
        - periodSeconds: 15
          type: Pods
          value: 5
        selectPolicy: Max
        stabilizationWindowSeconds: 0
    maxReplicas: 5
    metrics:
    - pods:
        metric:
          name: http_requests_per_second
        target:
          averageValue: "5"
          type: AverageValue
      type: Pods
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: product-service
  status:
    conditions:
    - lastTransitionTime: "2026-04-14T13:34:35Z"
      message: recommended size matches current size
      reason: ReadyForNewScale
      status: "True"
      type: AbleToScale
    - lastTransitionTime: "2026-04-14T13:34:35Z"
      message: the HPA was able to successfully calculate a replica count from pods
        metric http_requests_per_second
      reason: ValidMetricFound
      status: "True"
      type: ScalingActive
    - lastTransitionTime: "2026-04-14T13:45:37Z"
      message: the desired count is within the acceptable range
      reason: DesiredWithinRange
      status: "False"
      type: ScalingLimited
    currentMetrics:
    - pods:
        current:
          averageValue: 244m
        metric:
          name: http_requests_per_second
      type: Pods
    currentReplicas: 1
    desiredReplicas: 1
    lastScaleTime: "2026-04-14T13:49:23Z"
kind: List
metadata:
  resourceVersion: ""
