apiVersion: v1
items:
- apiVersion: keda.sh/v1alpha1
  kind: ScaledObject
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"keda.sh/v1alpha1","kind":"ScaledObject","metadata":{"annotations":{},"labels":{"experiment":"k1-keda"},"name":"product-service-keda","namespace":"ecommerce"},"spec":{"cooldownPeriod":30,"maxReplicaCount":5,"minReplicaCount":1,"pollingInterval":15,"scaleTargetRef":{"name":"product-service"},"triggers":[{"metadata":{"metricName":"http_requests_per_second","query":"sum(rate(http_requests_total{job=\"product-service\"}[1m]))\n","serverAddress":"http://prometheus.monitoring.svc.cluster.local:9090","threshold":"50"},"type":"prometheus"}]}}
    creationTimestamp: "2026-04-07T12:49:58Z"
    finalizers:
    - finalizer.keda.sh
    generation: 1
    labels:
      experiment: k1-keda
      scaledobject.keda.sh/name: product-service-keda
    name: product-service-keda
    namespace: ecommerce
    resourceVersion: "1052478"
    uid: a46d66b1-8001-4339-b541-a5b09f0ae527
  spec:
    cooldownPeriod: 30
    maxReplicaCount: 5
    minReplicaCount: 1
    pollingInterval: 15
    scaleTargetRef:
      name: product-service
    triggers:
    - metadata:
        metricName: http_requests_per_second
        query: |
          sum(rate(http_requests_total{job="product-service"}[1m]))
        serverAddress: http://prometheus.monitoring.svc.cluster.local:9090
        threshold: "50"
      type: prometheus
  status:
    authenticationsTypes: ""
    conditions:
    - message: ScaledObject is defined correctly and is ready for scaling
      reason: ScaledObjectReady
      status: "True"
      type: Ready
    - message: Scaling is performed because triggers are active
      reason: ScalerActive
      status: "True"
      type: Active
    - message: No fallbacks are active on this scaled object
      reason: NoFallbackFound
      status: "False"
      type: Fallback
    - status: Unknown
      type: Paused
    externalMetricNames:
    - s0-prometheus
    hpaName: keda-hpa-product-service-keda
    lastActiveTime: "2026-04-07T13:51:58Z"
    originalReplicaCount: 1
    scaleTargetGVKR:
      group: apps
      kind: Deployment
      resource: deployments
      version: v1
    scaleTargetKind: apps/v1.Deployment
    triggersTypes: prometheus
kind: List
metadata:
  resourceVersion: ""
