apiVersion: v1
items:
- apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"keda.sh/v1alpha1","kind":"ScaledObject","metadata":{"annotations":{},"labels":{"experiment":"k1-keda"},"name":"product-service-keda","namespace":"ecommerce"},"spec":{"cooldownPeriod":30,"maxReplicaCount":5,"minReplicaCount":1,"pollingInterval":15,"scaleTargetRef":{"name":"product-service"},"triggers":[{"metadata":{"metricName":"http_requests_per_second","query":"sum(rate(http_requests_total{job=\"product-service\"}[1m]))\n","serverAddress":"http://prometheus.monitoring.svc.cluster.local:9090","threshold":"5"},"type":"prometheus"}]}}
    creationTimestamp: "2026-04-14T14:18:28Z"
    labels:
      app.kubernetes.io/managed-by: keda-operator
      app.kubernetes.io/name: keda-hpa-product-service-keda
      app.kubernetes.io/part-of: product-service-keda
      app.kubernetes.io/version: main
      experiment: k1-keda
      scaledobject.keda.sh/name: product-service-keda
    name: keda-hpa-product-service-keda
    namespace: ecommerce
    ownerReferences:
    - apiVersion: keda.sh/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: ScaledObject
      name: product-service-keda
      uid: 433119ef-964c-4829-a0db-cbf7bd357774
    resourceVersion: "1644878"
    uid: 84dd19ab-909a-40c6-bb9b-cb19c5b31d91
  spec:
    maxReplicas: 5
    metrics:
    - external:
        metric:
          name: s0-prometheus
          selector:
            matchLabels:
              scaledobject.keda.sh/name: product-service-keda
        target:
          averageValue: "5"
          type: AverageValue
      type: External
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: product-service
  status:
    conditions:
    - lastTransitionTime: "2026-04-14T14:18:43Z"
      message: the HPA controller was able to update the target scale to 2
      reason: SucceededRescale
      status: "True"
      type: AbleToScale
    - lastTransitionTime: "2026-04-14T14:18:46Z"
      message: 'the HPA was able to successfully calculate a replica count from external
        metric s0-prometheus(&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name:
        product-service-keda,},MatchExpressions:[]LabelSelectorRequirement{},})'
      reason: ValidMetricFound
      status: "True"
      type: ScalingActive
    - lastTransitionTime: "2026-04-14T14:37:33Z"
      message: the desired count is within the acceptable range
      reason: DesiredWithinRange
      status: "False"
      type: ScalingLimited
    currentMetrics:
    - external:
        current:
          averageValue: 360m
        metric:
          name: s0-prometheus
          selector:
            matchLabels:
              scaledobject.keda.sh/name: product-service-keda
      type: External
    currentReplicas: 3
    desiredReplicas: 2
    lastScaleTime: "2026-04-14T14:38:03Z"
kind: List
metadata:
  resourceVersion: ""
