apiVersion: v1
items:
- apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"autoscaling/v2","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"labels":{"experiment":"h2-hpa-tuned"},"name":"product-service-hpa-tuned","namespace":"ecommerce"},"spec":{"behavior":{"scaleDown":{"policies":[{"periodSeconds":15,"type":"Percent","value":100}],"stabilizationWindowSeconds":30},"scaleUp":{"policies":[{"periodSeconds":15,"type":"Pods","value":5}],"stabilizationWindowSeconds":0}},"maxReplicas":5,"metrics":[{"resource":{"name":"cpu","target":{"averageUtilization":50,"type":"Utilization"}},"type":"Resource"}],"minReplicas":1,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"product-service"}}}
    creationTimestamp: "2026-04-07T10:21:28Z"
    labels:
      experiment: h2-hpa-tuned
    name: product-service-hpa-tuned
    namespace: ecommerce
    resourceVersion: "990588"
    uid: ece1c531-6d25-46b4-85a6-f510d9893bb7
  spec:
    behavior:
      scaleDown:
        policies:
        - periodSeconds: 15
          type: Percent
          value: 100
        selectPolicy: Max
        stabilizationWindowSeconds: 30
      scaleUp:
        policies:
        - periodSeconds: 15
          type: Pods
          value: 5
        selectPolicy: Max
        stabilizationWindowSeconds: 0
    maxReplicas: 5
    metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
      type: Resource
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: product-service
  status:
    conditions:
    - lastTransitionTime: "2026-04-07T10:21:43Z"
      message: recommended size matches current size
      reason: ReadyForNewScale
      status: "True"
      type: AbleToScale
    - lastTransitionTime: "2026-04-07T10:21:43Z"
      message: the HPA was able to successfully calculate a replica count from cpu
        resource utilization (percentage of request)
      reason: ValidMetricFound
      status: "True"
      type: ScalingActive
    - lastTransitionTime: "2026-04-07T10:35:59Z"
      message: the desired count is within the acceptable range
      reason: DesiredWithinRange
      status: "False"
      type: ScalingLimited
    currentMetrics:
    - resource:
        current:
          averageUtilization: 2
          averageValue: 2m
        name: cpu
      type: Resource
    currentReplicas: 1
    desiredReplicas: 1
    lastScaleTime: "2026-04-07T10:37:14Z"
kind: List
metadata:
  resourceVersion: ""
