apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"keda.sh/v1alpha1","kind":"ScaledObject","metadata":{"annotations":{},"labels":{"experiment":"k1-keda"},"name":"shipping-rate-service-keda","namespace":"ecommerce"},"spec":{"cooldownPeriod":30,"maxReplicaCount":5,"minReplicaCount":1,"pollingInterval":15,"scaleTargetRef":{"name":"shipping-rate-service"},"triggers":[{"metadata":{"metricName":"http_requests_per_second","query":"sum(rate(http_requests_total{job=\"shipping-rate-service\"}[1m]))\n","serverAddress":"http://prometheus.monitoring.svc.cluster.local:9090","threshold":"15"},"type":"prometheus"}]}}
  creationTimestamp: "2026-05-05T01:24:26Z"
  labels:
    app.kubernetes.io/managed-by: keda-operator
    app.kubernetes.io/name: keda-hpa-shipping-rate-service-keda
    app.kubernetes.io/part-of: shipping-rate-service-keda
    app.kubernetes.io/version: main
    experiment: k1-keda
    scaledobject.keda.sh/name: shipping-rate-service-keda
  name: keda-hpa-shipping-rate-service-keda
  namespace: ecommerce
  ownerReferences:
  - apiVersion: keda.sh/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ScaledObject
    name: shipping-rate-service-keda
    uid: 1c9971d8-e2d2-4cf1-807b-c29546a6cd3d
  resourceVersion: "2935519"
  uid: ca740f7b-c114-4840-ae64-b2f0dd0c6abf
spec:
  maxReplicas: 5
  metrics:
  - external:
      metric:
        name: s0-prometheus
        selector:
          matchLabels:
            scaledobject.keda.sh/name: shipping-rate-service-keda
      target:
        averageValue: "15"
        type: AverageValue
    type: External
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shipping-rate-service
status:
  conditions:
  - lastTransitionTime: "2026-05-05T01:24:41Z"
    message: recent recommendations were higher than current one, applying the highest
      recent recommendation
    reason: ScaleDownStabilized
    status: "True"
    type: AbleToScale
  - lastTransitionTime: "2026-05-05T01:24:41Z"
    message: 'the HPA was able to successfully calculate a replica count from external
      metric s0-prometheus(&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name:
      shipping-rate-service-keda,},MatchExpressions:[]LabelSelectorRequirement{},})'
    reason: ValidMetricFound
    status: "True"
    type: ScalingActive
  - lastTransitionTime: "2026-05-05T01:24:41Z"
    message: the desired count is within the acceptable range
    reason: DesiredWithinRange
    status: "False"
    type: ScalingLimited
  currentMetrics:
  - external:
      current:
        averageValue: 156m
      metric:
        name: s0-prometheus
        selector:
          matchLabels:
            scaledobject.keda.sh/name: shipping-rate-service-keda
    type: External
  currentReplicas: 3
  desiredReplicas: 3
  lastScaleTime: "2026-05-05T01:36:42Z"
