apiVersion: v1
items:
- apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"keda.sh/v1alpha1","kind":"ScaledObject","metadata":{"annotations":{},"labels":{"experiment":"k1-keda"},"name":"auth-service-keda","namespace":"ecommerce"},"spec":{"cooldownPeriod":30,"maxReplicaCount":5,"minReplicaCount":1,"pollingInterval":15,"scaleTargetRef":{"name":"auth-service"},"triggers":[{"metadata":{"metricName":"http_requests_per_second","query":"sum(rate(http_requests_total{job=\"auth-service\"}[1m]))\n","serverAddress":"http://prometheus.monitoring.svc.cluster.local:9090","threshold":"50"},"type":"prometheus"}]}}
    creationTimestamp: "2026-04-07T19:26:33Z"
    labels:
      app.kubernetes.io/managed-by: keda-operator
      app.kubernetes.io/name: keda-hpa-auth-service-keda
      app.kubernetes.io/part-of: auth-service-keda
      app.kubernetes.io/version: main
      experiment: k1-keda
      scaledobject.keda.sh/name: auth-service-keda
    name: keda-hpa-auth-service-keda
    namespace: ecommerce
    ownerReferences:
    - apiVersion: keda.sh/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: ScaledObject
      name: auth-service-keda
      uid: 45ae4f1c-42b3-4586-a353-e5babc7c9fde
    resourceVersion: "1170957"
    uid: 3f4c6aab-ba15-47cc-a6fb-a20721c904c2
  spec:
    maxReplicas: 5
    metrics:
    - external:
        metric:
          name: s0-prometheus
          selector:
            matchLabels:
              scaledobject.keda.sh/name: auth-service-keda
        target:
          averageValue: "50"
          type: AverageValue
      type: External
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: auth-service
  status:
    conditions:
    - lastTransitionTime: "2026-04-07T19:26:48Z"
      message: recommended size matches current size
      reason: ReadyForNewScale
      status: "True"
      type: AbleToScale
    - lastTransitionTime: "2026-04-07T19:26:48Z"
      message: 'the HPA was able to successfully calculate a replica count from external
        metric s0-prometheus(&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name:
        auth-service-keda,},MatchExpressions:[]LabelSelectorRequirement{},})'
      reason: ValidMetricFound
      status: "True"
      type: ScalingActive
    - lastTransitionTime: "2026-04-07T19:26:48Z"
      message: the desired count is within the acceptable range
      reason: DesiredWithinRange
      status: "False"
      type: ScalingLimited
    currentMetrics:
    - external:
        current:
          averageValue: 222m
        metric:
          name: s0-prometheus
          selector:
            matchLabels:
              scaledobject.keda.sh/name: auth-service-keda
      type: External
    currentReplicas: 1
    desiredReplicas: 1
- apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"keda.sh/v1alpha1","kind":"ScaledObject","metadata":{"annotations":{},"labels":{"experiment":"k1-keda"},"name":"product-service-keda","namespace":"ecommerce"},"spec":{"cooldownPeriod":30,"maxReplicaCount":5,"minReplicaCount":1,"pollingInterval":15,"scaleTargetRef":{"name":"product-service"},"triggers":[{"metadata":{"metricName":"http_requests_per_second","query":"sum(rate(http_requests_total{job=\"product-service\"}[1m]))\n","serverAddress":"http://prometheus.monitoring.svc.cluster.local:9090","threshold":"50"},"type":"prometheus"}]}}
    creationTimestamp: "2026-04-07T12:49:58Z"
    labels:
      app.kubernetes.io/managed-by: keda-operator
      app.kubernetes.io/name: keda-hpa-product-service-keda
      app.kubernetes.io/part-of: product-service-keda
      app.kubernetes.io/version: main
      experiment: k1-keda
      scaledobject.keda.sh/name: product-service-keda
    name: keda-hpa-product-service-keda
    namespace: ecommerce
    ownerReferences:
    - apiVersion: keda.sh/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: ScaledObject
      name: product-service-keda
      uid: a46d66b1-8001-4339-b541-a5b09f0ae527
    resourceVersion: "1170928"
    uid: f07cfc82-1b9a-4b2c-8d68-db77a8a37e3e
  spec:
    maxReplicas: 5
    metrics:
    - external:
        metric:
          name: s0-prometheus
          selector:
            matchLabels:
              scaledobject.keda.sh/name: product-service-keda
        target:
          averageValue: "50"
          type: AverageValue
      type: External
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: product-service
  status:
    conditions:
    - lastTransitionTime: "2026-04-07T12:50:13Z"
      message: recommended size matches current size
      reason: ReadyForNewScale
      status: "True"
      type: AbleToScale
    - lastTransitionTime: "2026-04-07T17:00:26Z"
      message: 'the HPA was able to successfully calculate a replica count from external
        metric s0-prometheus(&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name:
        product-service-keda,},MatchExpressions:[]LabelSelectorRequirement{},})'
      reason: ValidMetricFound
      status: "True"
      type: ScalingActive
    - lastTransitionTime: "2026-04-07T12:50:13Z"
      message: the desired count is within the acceptable range
      reason: DesiredWithinRange
      status: "False"
      type: ScalingLimited
    currentMetrics:
    - external:
        current:
          averageValue: 244m
        metric:
          name: s0-prometheus
          selector:
            matchLabels:
              scaledobject.keda.sh/name: product-service-keda
      type: External
    currentReplicas: 1
    desiredReplicas: 1
    lastScaleTime: "2026-04-07T13:09:30Z"
kind: List
metadata:
  resourceVersion: ""
