apiVersion: v1
kind: Service
metadata:
  name: shipping-rate-service
  namespace: ecommerce
spec:
  selector:
    app: shipping-rate-service
  ports:
    - protocol: TCP
      port: 8006
      targetPort: 8006
  type: ClusterIP
